### ISSUE TITLE
Two problems found with brew-cask.sh

### ISSUE THREAD

**Issue by hao-lh** [eduncan911/dotfiles#1] opened 2016-05-10 02:55 UTC
The brew-cask.sh script is great for batch update via command, but with two issues found currently:
1. Users occasionally could update the application via In-App update item, and this scripts would force downloading and updating again, thus, seemed need to check the app version before update?
2. Sometimes users are faced with sha256 mismatch problem, and this scripts would not download and update it anymore since files are already downloaded into directory, and users have to remove the download file manually and I was wondering if you can remove the pre-download files in the script?

Hope the above two issues can be fixed, many thanks!

**Comment by eduncan911** [comment] 2016-05-10 18:20
Excellent!  My first feedback on `dotfiles`!  Thank you!  👍 

Note that you hit home on the version issue I have with **Homebrew** in general as a package manager: it has next to nil support for revisions like `aptitude` and `pacman` for example.  There are serious limitations to Homebrew in general in regards to that.

But, it is even worse with **Cask**...  In what features that Homebrew is lacking, Cask lacks even some of the basic features of Homebrew itself (such as version tracking!  it only knows what `brew update` has, not what is installed).  There's also no dependency tracking, like Homebrew has (though _extremely_ limited and only for the current version, not past versions).  Therefore, scripts like mine are basically work arounds with these limitations.

Basically: my script _**compares what the latest version is available to the directory name local to your disk of where the application is installed**_.  This is the fundamental limitation of Caskroom, and the only way to compare things.

homebrew-cask cannot always detect updates.  Therefore, the official way to get anything installed is with `brew cask install --force {caskname}`.  Using `brew upgrade --all` does not always upgrade packages I've noticed.

My script basically:
- gets a list of all Casks locally with `brew cask list`.
- iterate and query each Cask item with `brew cask info {caskname}` <- NOTE: this only returns what version that your latest `brew update` has available.  There is no way to "list" what version you have installed using the Cask tooling.
- parse get the version number reported by said Cask based on the `brew update` version available.
- parse the 'current version installed' from basically looking at all sub-directories of `/opt/homebrew-cask/Caskroom/{caskname}/{versions}`
- compare each version to see if it is listed.  if not listed, upgrade/mark as upgrade available.

For #1, the issue is that it doesn't know what version of the app is "installed/update".  We can only know based on the Directory Name that `brew cask install ...` installed it into, which happens to be a version number like `/opt/homebrew-cask/Caskroom/atom/1.7.3/`.  As to what the application version number actually is within that directory, who knows!  It's up in the air. 

I think the other issue is that **homebrew-cask** typically expects users to evaluate the In-App updatability on a per application basis.  

> - Can it update itself?  (e.g. Chrome)   If yes, then leave the cask alone and let it update the location that Homebrew installed.  Don't upgrade.
> - No internal updater?  Use `brew cask install --force {caskname}` to force an update based on the version from `brew update` tap of `caskroom`.  Or, uninstall first and then install again for latest (ick).

My script forces an update regardless.  Therefore, these are the rules I follow when using the **homebrew-cask** tap:
- Does the app have an auto-updater?  (Chrome, Atom, etc)  Don't use Cask, go download the app from official locations and install it outside of Cask.
- Does the app not have a way to update itself; or, is it limited/annoying in the way it updates itself?  (e.g. Karabiner)  Install it with `brew cask install {caskname}` like normal, and disable all updating notifications itself.  I want Cask to just force install each new version whenever available.  I don't need to be told "Hey, there's a new version available for download!"  

For example, i install Chrome normally by downloading from Chrome's main site.  It auto-updates itself. 

As for #2, I am no Homebrew expert but I think that's what is what `brew cleanup -s` is for (note, use `brew cleanup -ns` to test it first).  Unfortunately this is only works for normal homebrew packages - not Caskroom!

I haven't seen this mismatch issue before though.  Could you elaborate?  

As far as removing pre-downloaded files... I've thought of it; but, the way brew and casks are downloaded to and compared is kind of all over the place.  I'd rather let the tooling do that itself.  

For example: Dependencies that are no longer used, how do you want to clean them up?  There is no clear way to do that with Homebrew itself.  With Cask?  Ha, non-existent.

**Comment by hao-lh** [comment] 2016-05-10 18:48
Thank you so much for your so detailed reply!
I understand it is basically due to brew cask's limited supporting features. And one more advice for the scripts, when users run the script, it begins downloading, followed by installing procedure for each package, and at the installing stage the network is actually idle, and I was wondering it can be improved by downloading the packages need to be updated continually or even with multiple threads, which would greatly save user's time and improve efficiency. Thanks!

**Comment by eduncan911** [comment] 2016-05-10 22:29
Good idea.  Though, `parallel` isn't installed by default (the easy way to do concurrent batch jobs on the CLI).

But concurrency comes with a price: what if one fails?  You need interop communications to communicate back to the host process to 'stop' when it fails.  There's also the issue with multiple items writing to the console at the same time (they would intermix).  

Honestly, all of that seems like way more work than I'm willing to invest into a simple script that takes about 30 seconds to run.  

I run mine often, about once a week, with about 17 Cask packages.  I only see 1 or 2 updates a month; hardly anything to make concurrent.  The most I've seen at once was 5 - which made me evaluate if I even wanted them under Homebrew to begin with...

...because really, any UI application under Caskroom is a risk to install because they are all basically hacks around OSX native UI to get things to install without user input.

**Comment by eduncan911** [comment] 2016-07-22 17:39
Going to close this as it works.  someone that wants to time to parallelize it could if they like.  👍

**Closed as completed by eduncan911** 2016-07-22 17:39 UTC
